/** Compile the approved Plastic artboards into portable, inlined email HTML. */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import postcss from 'postcss';

const root = new URL('../emails/', import.meta.url);
const manifest = JSON.parse(await readFile(new URL('manifest.json', root), 'utf8'));
const css = await readFile(new URL('design/styles.css', root), 'utf8');
const tokens = await readFile(new URL('design/tokens.css', root), 'utf8');
const variables = Object.fromEntries([...tokens.matchAll(/(--[\w-]+)\s*:\s*([^;}]+)/g)].map((m) => [m[1], m[2].trim()]));
const templates = {};
for (const template of manifest.templates) {
  const dom = new JSDOM(await readFile(new URL(`design/${template.page}`, root), 'utf8'));
  const document = dom.window.document;
  const frame = document.querySelector(`[data-pl-id="${template.frame}"]`);
  if (!frame) throw new Error(`Missing frame: ${template.frame}`);
  document.body.replaceChildren(frame);
  frame.classList.remove('email-shell-mobile');
  const styles = new Map();
  postcss.parse(css).walkRules((rule) => {
    if (rule.selector.includes('.email-shell-mobile')) return;
    for (const element of document.querySelectorAll(rule.selector)) {
      const declarations = styles.get(element) ?? new Map();
      rule.walkDecls((decl) => {
        const old = declarations.get(decl.prop);
        if (!old?.important || decl.important)
          declarations.set(decl.prop, {
            value: decl.value.replace(/var\((--[\w-]+)\)/g, (_, name) => variables[name]),
            important: decl.important,
          });
      });
      styles.set(element, declarations);
    }
  });
  for (const [element, declarations] of styles) {
    element.setAttribute(
      'style',
      [...declarations].map(([prop, decl]) => `${prop}:${decl.value}${decl.important ? '!important' : ''}`).join(';'),
    );
  }
  for (const element of document.querySelectorAll('[data-email-field]')) {
    const field = element.getAttribute('data-email-field');
    if (element.tagName === 'A') element.setAttribute('href', `{{${field}}}`);
    else element.textContent = `{{${field}}}`;
  }
  for (const image of document.querySelectorAll('img')) {
    image.setAttribute('src', `{{assetOrigin}}/emails/${image.getAttribute('src').split('/').pop()}`);
    image.setAttribute('alt', image.getAttribute('alt') ?? '');
  }
  // Lucide's exact ArrowUpRight paths are rasterized at 3x for mail clients without SVG.
  for (const svg of document.querySelectorAll('.email-action-icon')) {
    const image = document.createElement('img');
    image.setAttribute('src', '{{assetOrigin}}/emails/arrow-up-right.png');
    image.setAttribute('alt', '');
    image.setAttribute('width', '14');
    image.setAttribute('height', '14');
    image.setAttribute('style', svg.getAttribute('style'));
    svg.replaceWith(image);
  }
  for (const element of document.querySelectorAll('*')) {
    for (const attribute of [...element.attributes]) if (attribute.name.startsWith('data-')) element.removeAttribute(attribute.name);
  }
  frame.setAttribute('width', '100%');
  frame.setAttribute('align', 'center');
  frame.setAttribute('style', frame.getAttribute('style').replace('width:640px', 'width:100%;max-width:640px'));
  // Preserve paragraphs, headings and links in the accessible plain-text alternative.
  const textFrame = frame.cloneNode(true);
  for (const link of textFrame.querySelectorAll('a')) link.append(` (${link.getAttribute('href')})`);
  for (const br of textFrame.querySelectorAll('br')) br.replaceWith('\n');
  for (const block of textFrame.querySelectorAll('p,h1,h2,td')) block.append('\n\n');
  const text = textFrame.textContent
    .replace(/[ \t]+/g, ' ')
    .replace(/ *\n */g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${template.subject}</title><style>@media(max-width:480px){.email-padding{padding:16px!important}.email-content{padding:28px 24px!important}.email-heading{font-size:32px!important;letter-spacing:-1.3px!important}}</style></head><body style="margin:0;padding:0;background:${variables['--color-canvas']}"><div style="display:none;max-height:0;overflow:hidden;mso-hide:all">${template.preheader}</div>${frame.outerHTML}</body></html>`;
  templates[template.id] = { subject: template.subject, html, text };
}
await mkdir(new URL('../worker/generated/', root), { recursive: true });
await writeFile(
  new URL('../worker/generated/email-templates.ts', root),
  `// Generated by scripts/build-emails.mjs from the approved Plastic file.\nexport const emailTemplates = ${JSON.stringify(templates, null, 2)} as const;\n`,
);
console.log(`Compiled ${Object.keys(templates).length} approved email templates.`);
